---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.9.1 提供了几项新功能和增强功能。 
---
= Cloud Volumes ONTAP 9.9.1 中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.9.1 提供了几项新功能和增强功能。

最新版本的 Cloud Manager 还引入了其他功能和增强功能。请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager 发行说明"^] 了解详细信息。



== 不再支持c4、m4和r4实例(2022年10月28日)

在AWS中、Cloud Volumes ONTAP 不再支持C4、M4和M4 EC2实例类型。如果现有系统运行的是C4、M4或r4实例类型、则必须更改为c5、M5或R5实例系列中的实例类型。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["了解如何更改Cloud Volumes ONTAP 的EC2实例类型"^]。

请参见 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 支持"^] 了解有关这些实例类型的可用性和支持终止的更多信息。



== 9.9.1 P8 (2022年5月15日)

如果您的Connector运行的是3.9.13或更高版本、则现在可以在Microsoft Azure中为Cloud Volumes ONTAP 提供9.9.1 P8修补程序。Cloud Manager 将提示您将现有系统升级到此修补程序版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P8["查看 P8 修补程序中已修复的错误列表"^] （需要登录 NetApp 支持站点）。



== 9.9.1 P7 （ 2022 年 2 月 21 日）

现在，如果您的 Connector 运行的是 3.9.15 或更高版本，则可以在 Microsoft Azure 中为 Cloud Volumes ONTAP 提供 9.9.1 P7 修补程序。Cloud Manager 将提示您将现有系统升级到此修补程序版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P7["查看 P7 修补程序中已修复的错误列表"^] （需要登录 NetApp 支持站点）。



== 9.9.1 修补程序（ 2022 年 2 月 3 日）

Cloud Volumes ONTAP 提供了两个新修补程序：

* AWS 和 Google Cloud 中的 9.9.1 P6
* Microsoft Azure 中的 9.9.1 P3


Cloud Manager 将提示您将现有系统升级到这些修补程序版本。

* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P6["查看 P6 修补程序中已修复的错误列表"^] （需要登录 NetApp 支持站点）
* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P3["查看 P3 修补程序中已修复的错误列表"^] （需要登录 NetApp 支持站点）




== 9.9.1 GA （ 2021 年 7 月 21 日）

Cloud Volumes ONTAP 9.9.1 的通用版本（ GA ）现已推出。GA 版本包含错误修复。

Cloud Manager 将提示您升级运行以下任一版本的现有系统： 9.9.1 Release candidate ， 9.0.0 或 9.8 。



== 9.9.1 更新（ 2021 年 7 月 7 日）

Cloud Manager 3.9.8 版引入了以下变更。

* Cloud Volumes ONTAP 提供了新的充电方法。
+
** * 基于容量的 BYOL* ：通过基于容量的许可证，您可以按每 TiB 容量为 Cloud Volumes ONTAP 付费。此许可证与您的 NetApp 帐户关联，只要您的许可证具有足够的容量，您就可以创建多个 Cloud Volumes ONTAP 系统。基于容量的许可以软件包的形式提供，可以是 _Essentials 或 _Professional 。
** * 免费提供 * ：免费使用 NetApp 提供的所有 Cloud Volumes ONTAP 功能（云提供商仍需付费）。每个系统的已分配容量限制为 500 GiB ，并且没有支持合同。您最多可以有 10 个免费系统。
+
link:concept-licensing.html["详细了解这些许可选项"]。



* 在 AWS 中， Cloud Volumes ONTAP 现在支持采用以下充电方法的 m5dn.24xlarge 实例类型： PAYGO Premium ，基于容量的许可证（ BYOL ）和基于节点的许可证（ BYOL ）。
* 在 Google Cloud 中， Cloud Volumes ONTAP 现在支持平衡持久性磁盘（ PD 平衡）。这些 SSD 通过提供更低的每 GiB IOPS 来平衡性能和成本。
* Google Cloud 中的新 Cloud Volumes ONTAP 系统不再支持 custom-4-16384 计算机类型。
+
如果您的现有系统在此计算机类型上运行，则可以继续使用它，但我们建议切换到 n2-standard-4 计算机类型。



https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["详细了解 Cloud Manager 中的新增功能"^]。



== 9.9.1 更新（ 2021 年 6 月 3 日）

最近的 Cloud Manager 3.9.7 版支持一个新的专业软件包，通过该软件包，您可以使用 AWS Marketplace 提供的年度合同捆绑 Cloud Volumes ONTAP 和 Cloud Backup Service 。

link:reference-configs-aws.html["了解有关此许可选项的更多信息。"]



== 9.9.1 候选版本（ 2021 年 5 月 24 日）

Cloud Volumes ONTAP 9.9.1 候选版本现已在 AWS ， Azure 和 Google 云平台中推出。

除了提供的功能之外，还提供了 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.9.1"^]，此版本的 Cloud Volumes ONTAP 包括以下内容：

* <<Azure 中的 ONTAP S3 支持>>
* <<在 AWS 中提高性能并提高写入速度>>
* <<AWS 中的 IO2 启动磁盘>>




=== Azure 中的 ONTAP S3 支持

现在，您可以从 Azure 中的 Cloud Volumes ONTAP 提供 S3 对象存储。Cloud Volumes ONTAP for Microsoft Azure 除了支持 NFS 和 SMB 等基于文件的传统协议之外，还支持将 S3 作为横向扩展存储的一个选项。

请注意以下事项：

* 采用 Cloud Volumes ONTAP 的 ONTAP S3 的主要用例是通用对象存储。
* 目前， AWS 或 Google Cloud 中的 Cloud Volumes ONTAP 不支持 S3 协议。
* Cloud Manager 不为 ONTAP S3 功能提供任何管理功能。


最好使用命令行界面从 Cloud Volumes ONTAP 配置 S3 客户端访问。有关详细信息，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["《 S3 配置高级指南》"^]。



=== 在 AWS 中提高性能并提高写入速度

我们提高了 Cloud Volumes ONTAP 在以下情况下的吞吐量性能 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["高写入速度"^] 在支持的实例类型上启用。



=== AWS 中的 IO2 启动磁盘

在 AWS 中，新 Cloud Volumes ONTAP 系统的启动磁盘现在是已配置的 IOPS SSD （ IO2 ）卷。IO2 卷提供的可靠性比 IO1 卷更高，而 IO1 卷以前用于启动磁盘。



== 所需版本的 Cloud Manager Connector

要部署新的 Cloud Volumes ONTAP 9.9.1 系统并将现有系统升级到 9.9.1 ， Cloud Manager Connector 必须运行 3.9.6 或更高版本。



== 升级说明

* Cloud Volumes ONTAP 升级必须从 Cloud Manager 完成。您不应使用 System Manager 或命令行界面升级 Cloud Volumes ONTAP 。这样做可能会影响系统稳定性。
* 您可以从 9.9.0 版和 9.8 版升级到 Cloud Volumes ONTAP 9.9.1 版。Cloud Manager 将提示您将现有 Cloud Volumes ONTAP 9.9.0 和 9.8 系统升级到 9.9.1 版本。
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["了解在 Cloud Manager 通知您时如何升级"^]。

* 升级单节点系统会使系统脱机长达 25 分钟，在此期间 I/O 会中断。
* 升级 HA 对无中断， I/O 不会中断。在此无中断升级过程中，每个节点会同时进行升级，以继续为客户端提供 I/O 。




=== DS3_v2

从 9.9.1 版开始，新的和现有的 Cloud Volumes ONTAP 系统不再支持 DS3_v2 VM 类型。如果您的现有系统在此 VM 类型上运行，则需要在升级到 9.1.1 之前更改 VM 类型。
